name: Build, test and release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Build Drutiny Phar
        id: drutiny-build
        uses: AmazeeLabs/drutiny_build_github_action@v0.0.5
        with:
          tag-ref: ${{ steps.get-tag.outputs.tag }}
          composer-packages: "bomoko/algm_drutiny_profile:dev-master, bomoko/lagoon-formatter:dev-master"
          composer-repos: "bomoko/algm_drutiny_plugin vcs https://github.com/AmazeeLabs/algm_drutiny.git"

      - name: Change Directory
        run: cd ./drutiny && ls -la

      - name: 'Echo download path'
        run: echo ${{steps.drutiny-build.outputs.phar}}

      - name: Upload phar as artifact
        uses: actions/upload-artifact@v2
        with:
          name: phar
          path: "**/*drutiny*.phar"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download phar artifact from build step
        id: download
        uses: actions/download-artifact@v2
        with:
          name: phar
          path: ./

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Display structure of downloaded files
        run: ls -R

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Bump version and create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.get-tag.outputs.tag }}
          tag: ${{ steps.get-tag.outputs.tag }}
          body: 'Next stable release.'
          allowUpdates: true
          artifacts: "**/*drutiny*.phar"
          artifactContentType: application/x-php
